#!/usr/bin/env python3
"""Read-only repository inventory and RepoMeld candidate scan.

This script intentionally does not edit or delete anything. It emits JSON candidates
for semantic review by RepoMeld agents.
"""
from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path

DEFAULT_SKIP = {
    ".git", ".hg", ".svn", "node_modules", "vendor", "dist", "build", "target",
    ".next", ".nuxt", ".venv", "venv", "__pycache__", ".cache", "coverage",
}

MANIFESTS = {
    "package.json", "pnpm-workspace.yaml", "yarn.lock", "package-lock.json",
    "pyproject.toml", "requirements.txt", "poetry.lock", "Cargo.toml", "go.mod",
    "pom.xml", "build.gradle", "build.gradle.kts", "settings.gradle", "Makefile",
    "CMakeLists.txt", "Gemfile", "composer.json", "mix.exs", "deno.json", "deno.jsonc",
}

TEXT_SUFFIXES = {
    ".py", ".js", ".jsx", ".ts", ".tsx", ".java", ".kt", ".kts", ".go", ".rs",
    ".c", ".h", ".cc", ".cpp", ".hpp", ".cs", ".rb", ".php", ".swift", ".scala",
    ".sh", ".bash", ".zsh", ".fish", ".ps1", ".sql", ".yaml", ".yml", ".toml",
    ".json", ".md", ".mdx", ".rst", ".txt", ".ini", ".cfg", ".conf", ".xml",
}

TRACE_PATTERNS = [
    ("stage_marker", re.compile(r"\b(?:S\d+|M\d+|Phase\s+\d+|Step\s+\d+|Task\s+\d+(?:\.\d+)*)\b", re.I)),
    ("agent_narration", re.compile(r"\b(?:as discussed above|we now need to|for the purpose of this task|ai[- ]generated|generated by (?:ai|agent))\b", re.I)),
    ("temporary_wording", re.compile(r"\b(?:temporary|scratch|debug|verification report|implementation notes?|status report)\b", re.I)),
]

TEMP_NAME_PATTERNS = [
    re.compile(r"^(?:tmp|temp|scratch|debug)[-_].*", re.I),
    re.compile(r".*[-_](?:analysis|report|plan|status|notes?)\.(?:md|txt|json|yaml|yml)$", re.I),
    re.compile(r"^(?:analysis|verification|implementation)[-_].*\.(?:md|txt|json)$", re.I),
]


def should_skip_dir(name: str, extra: set[str]) -> bool:
    return name in DEFAULT_SKIP or name in extra


def is_text_candidate(path: Path) -> bool:
    return path.suffix.lower() in TEXT_SUFFIXES or path.name in MANIFESTS


def scan_file(path: Path, root: Path, max_bytes: int) -> list[dict]:
    out = []
    try:
        if path.stat().st_size > max_bytes:
            return out
        text = path.read_text(encoding="utf-8", errors="ignore")
    except (OSError, UnicodeError):
        return out
    rel = str(path.relative_to(root))
    for lineno, line in enumerate(text.splitlines(), 1):
        for category, pattern in TRACE_PATTERNS:
            if pattern.search(line):
                out.append({
                    "path": rel,
                    "line": lineno,
                    "category": category,
                    "sample": line.strip()[:300],
                })
    return out


def infer_top_level_modules(root: Path) -> list[str]:
    modules = []
    for child in sorted(root.iterdir(), key=lambda p: p.name.lower()):
        if child.is_dir() and child.name not in DEFAULT_SKIP and not child.name.startswith("."):
            modules.append(child.name)
    return modules


def main() -> int:
    ap = argparse.ArgumentParser(description="Read-only RepoMeld repository scan")
    ap.add_argument("root", nargs="?", default=".")
    ap.add_argument("--max-file-bytes", type=int, default=1_000_000)
    ap.add_argument("--skip", action="append", default=[], help="Additional directory name to skip")
    ap.add_argument("--pretty", action="store_true")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    if not root.is_dir():
        raise SystemExit(f"Not a directory: {root}")

    extra_skip = set(args.skip)
    manifests = []
    temp_name_candidates = []
    trace_candidates = []
    file_count = 0

    for current, dirs, files in os.walk(root):
        dirs[:] = [d for d in dirs if not should_skip_dir(d, extra_skip)]
        cur = Path(current)
        for name in files:
            path = cur / name
            file_count += 1
            rel = str(path.relative_to(root))
            if name in MANIFESTS:
                manifests.append(rel)
            if any(p.match(name) for p in TEMP_NAME_PATTERNS):
                temp_name_candidates.append(rel)
            if is_text_candidate(path):
                trace_candidates.extend(scan_file(path, root, args.max_file_bytes))

    result = {
        "repository_root": str(root),
        "file_count": file_count,
        "top_level_modules": infer_top_level_modules(root),
        "manifests": sorted(manifests),
        "temporary_name_candidates": sorted(set(temp_name_candidates)),
        "trace_candidates": trace_candidates,
        "notice": "Candidates only. RepoMeld semantic review is required before mutation or deletion."
    }
    print(json.dumps(result, indent=2 if args.pretty else None, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
